### ISSUE TITLE
Send core name over an HDMI infoframe when not in DV1 mode

### ISSUE THREAD

**Issue by spinek2** [MiSTer-devel/Main_MiSTer#1057]
Hello, I am not sure if I am posting in the right place. If not, I apologise. Today, on the Morph4k channel, I raised the issue of rotation, which is not yet available on this scaler. All the cores that are important to me use DV1 and everything is fine. The problem is, of course, with the Arcade Tate cores, because they have DV1 disabled so that they display correctly on a horizontal television. Unfortunately, all Arcade Tate cores are then treated like everything else in 1080p. If I now use mask settings in Morph, e.g. for Pooyan, then Galaga inherits these settings and does not look good anymore. The same with BFI - it is enabled for all 1080p things, and we know how different arcade cores are. 
And now one of the creators of Morph mentioned that I should ask for ‘send core name over an HDMI infoframe when not in DV1 mode’, then the problem with the diversity of Arcade Tate cores without DV1 should be solved 🙂

On Discord RetroTINK, one of the advanced members informed me that rotation in the PRO version of the scaler has its problems related to the high load on the FPGA chip, and then there may be problems with, for example, CRT beam simulation and other CRT effects. 

It would also be great if the scalers ‘knew’ which specific Arcade Tate core was running without DV1. Then each one could be individually configured in the scaler.

 I apologise for the chaos in this text, but I don't think in English 🙂

**Comment by sorgelig** [comment]
May be it's possible. I don't have these scalers, so probably some one having such scaler can add it.

**Comment by spinek2** [comment]
Sorgelig, thank you for taking an interest in this matter. You are a true legend to me. This would be a big deal for the part of the community that uses scalers and loves Arcade Tate games. At the moment, only RetroTINK Pro uses rotation, but its users would also have the choice of whether to use the scaler's rotation or Mister FPGA. For other users, this would be an amazing feature. 
I will ask competent people for technical support and I hope that together you will be able to add such a great feature :)

**Comment by Gawthepopful** [comment]
The Morph already configured to accept data from the spd infoframe and also through cec without dv1. So from dev standpoint on scaler side, nothing is required. My understanding is the functionality needs to come from the MiSTer side of things specifically. Porkchop already has a fork of the Menu that adds GameID support, but currently that data is not sent over hdmi. I think just the core name would work for arcade cores. Let us know how we can help.

**Comment by Gawthepopful** [comment]
I’ve written a script that logs the core name and sends a curl http command to the Morph that will load a profile based on the loaded core, and it works, but it’s not always reliable, as the MiSTer isn’t designed to do such things. Would be much more elegant to just add that data over the hdmi infoframe like it does over dv1. Only needs core name. The morph can apply auto presets just by unique spd info.

**Comment by spinek2** [comment]
Hi, Sorgelig. Do you think it will be possible to do something about what Gaw wrote?

**Comment by sorgelig** [comment]
As i wrote above, i don't have these scalers. So i don't know how it works.

**Comment by woozle64** [comment]
Hi, I'm one of the developers for the Morph 4K. If you'd like a Morph to try out with MiSTer (no strings attached), I would happily send one your way. Just need shipping info (not sure where to exchange that, only social media I use is Discord under the username woozle64). Thanks for all you do on the MiSTer project btw :)

**Comment by birdybro** [comment]
Also I believe @zakk4223 has one or both of these scalers.

**Comment by zakk4223** [comment]
As it stands now:
Freesync over HDMI uses the SPD info frame
HDMI Forum VRR uses one of the adv7513 'spare packets'.
HDR uses the other 'spare'.

DV1 also uses the spd frame, which is fine because DV1 and VRR are mutually exclusive.

I think it would be reasonable to assume the 'fake' vrr is useless when doing normal HDMI to these scalers and we could just use the SPD frame and send a vendor name of 'MiSTer' with a product description that's the same thing as DV1 does: the core name/setname. 

Should be pretty straightforward, I'll put something together and test it.

**Comment by Gawthepopful** [comment]
Thank you for the consideration. I think this could very helpful in many
cases, especially where dv1 has been problematic where cores send wrong
info or if switching hardware messes with the signal.

**Comment by zakk4223** [comment]
@sorgelig it looks like there was already code that did this (if not DV1 and not freesync_vrr then send spd with core name info). 

It was commented out in this commit: https://github.com/MiSTer-devel/Main_MiSTer/commit/613f808ffbf5ef57fd835504730e87cb06381585

Do you remember if there was something problematic with some displays if it was set? Do we need to maybe make it opt-in via some ini variable? Otherwise it seems to work perfectly with the morph4k and let's you load profiles based on core name.

**Comment by sorgelig** [comment]
I know, the code is there but it's not enabled for non-DV and i don't know if it will affect any display. I only have one TV and couple of monitors ;)

Ok, i've pushed the commit. Currently it sends SPD always. Let's see if there will be complains.
Added flag 0x8 in SPD to show it's not direct video mode, so scalers can distinguish it.

**Comment by zakk4223** [comment]
I think most (all?) of them currently use the 'DV1' "vendor" string to trigger their DV1 specific scaling. They will all need to push firmware changes; without it users will not be able to disable DV1 mode selectively.

Until those firmware updates are done and users update, this is a very disruptive change. (my non-DV1 setup through a morph is now unusable) A lot of  users disable DV1 for the menu core and some problematic cores.  It might be best to use another vendor string when DV1 is not active, maybe just 'MiSTer' 

edit: this also breaks vrr_mode=2/vrr_mode=1 where freesync is detected

**Comment by Gawthepopful** [comment]
Rather than requiring a FW update on scalers, changing the vendor to anything other than DV1 should fix the current issue. It’s also broken on the RT4K.

**Comment by sorgelig** [comment]
Ok. Changed to "VI1".

**Comment by zakk4223** [comment]
Vrr still broken.

How does the RT4K use this info? On the morph it uses the vendor as a directory name to auto-load profiles. so By_SPD/VI1/c/corename. I guess that works.

**Comment by jesusburnsneon** [comment]
@zakk4223 - RT4K offers the option to use a /dv1 folder to manage and load custom profiles for MiSTer cores (or any other device supporting DV1 e.g. Pixel FX xDigital / Retro GEM).   Then by enabling Auto DV1 Load, RT4K will automatically assign the custom profile after it detects the dv1 input device via the SPD Infoframe.  

Snippets from RT4K wiki:

<img width="1030" height="251" alt="Image" src="https://github.com/user-attachments/assets/96340636-e219-4530-83a4-c2ada496b504" />

<img width="1000" height="142" alt="Image" src="https://github.com/user-attachments/assets/b6077541-0cf0-4f6d-b0cd-67c3aeaac951" />

**Comment by woozle64** [comment]
Perhaps the SPD info frame could just be sent with vendor:product as MiSTer:core_name. This would work fine with the Morph 4K, should also be easy for any future scaler to work with.

chriz2600 wrote the code below and verified it worked on his MiSTer

```static void spd_config_update()
{
    if (cfg.direct_video)
    {
        // Custom SPD IF for additional DV1 metadata
        VideoInfo *vi = &current_video_info;
        if (!vi->width)
            return;

        uint8_t data[32] = {
            0x83, 0x01, 25, 0,
            'D',
            'V',
            '1', // version
            (uint8_t)((vi->interlaced ? 1 : 0) | (menu_present() ? 4 : 0)),
            (uint8_t)(vi->pixrep ? vi->pixrep : (vi->ctime / vi->width)),
            (uint8_t)vi->de_h,
            (uint8_t)(vi->de_h >> 8),
            (uint8_t)vi->de_v,
            (uint8_t)(vi->de_v >> 8),
            (uint8_t)vi->width,
            (uint8_t)(vi->width >> 8),
            (uint8_t)vi->height,
            (uint8_t)(vi->height >> 8)
        };

        char *name = user_io_get_core_name2();
        for (int i = 17; i < 32; i++)
        {
            if (!*name) break;
            data[i] = (uint8_t)(*name);
            name++;
        }

        spd_config(data);
    }
    else
    {
        // Standard SPD IF
        uint8_t data[32] = {
            0x83, 0x01, 25,                        // SPD IF header + length
            0,                                    // Checksum, automatically calculated by ADV7513 if zero
            'M', 'i', 'S', 'T', 'e', 'r', 0, 0, // Vendor Name (up to 8 characters)
        };

        // Product Description (up to 16 characters)
        char *name = user_io_get_core_name2();
        for (int i = 12; i < 28; i++)
        {
            if (!*name) break;
            data[i] = (uint8_t)(*name);
            name++;
        }

        // Source Information (see ANSI/CTA-861-I, Table 35 - Source Product Description InfoFrame Data Byte 25)
        data[28] = 0x08; // Type: Game

        spd_config(data);
    }
}```

**Comment by TheJesusFish** [comment]
I realize that this has become a real “road to hell is paved with good intentions” situation, sorg. But, you know, while you’re in there https://github.com/MiSTer-devel/Main_MiSTer/issues/982 😄

**Comment by Gawthepopful** [comment]
This code is working perfectly.

**Comment by sorgelig** [comment]
@zakk4223 
> Vrr still broken.

It's not clear if you use one of these scalers and put video through it, or you use direct to TV connection? Which TV do you use?

**Comment by sorgelig** [comment]
> I realize that this has become a real “road to hell is paved with good intentions” situation, sorg. But, you know, while you’re in there [#982](https://github.com/MiSTer-devel/Main_MiSTer/issues/982) 😄

added rotation flag.

**Comment by TheJesusFish** [comment]
Ok, Pandora's InfoFrame remains open.

@sorgelig Here is where we stand right now:

Working:
- VRR

Not Working
- Direct Video Rotation flag (reports zero regardless of the rotation of the game)
- HDMI SPD info frame spits out garbage rather than the core info

Requests:
- MiSTer as the vendor name instead of VI1
- Direct Video Rotation Flag supports direction (0 for no rotation, 1 for cw, and 2 for ccw) - I can take a crack at this if you prefer (once the flag is fixed).

Thanks as always for your work with this, duder. Sorry that this request is the gift that keeps on giving.

(Screenshots taken on the morph because the tink4k just displays the info frame in hex)

<img width="1280" height="960" alt="Image" src="https://github.com/user-attachments/assets/98066b08-3781-4935-960a-0698bd85c058" />
<img width="1280" height="960" alt="Image" src="https://github.com/user-attachments/assets/05d11f5a-9586-4cd8-a7da-74188bedc848" />
<img width="1280" height="960" alt="Image" src="https://github.com/user-attachments/assets/f8c3c502-aed9-470b-9389-279b7ddffcce" />

**Comment by sorgelig** [comment]
Rotation flag in DV won't work. It works only in normal hdmi output. Rotation is disabled in DV mode.

Does your scaler already supports VI1 header? Probably it doesn't. It should support VI1 header explicitly, not like generic one. Basically it's the same as DV1 header with additional info from core.

**Comment by TheJesusFish** [comment]
> Rotation flag in DV won't work. It works only in normal hdmi output. Rotation is disabled in DV mode.

Could main pull the information from the MRA to get the rotation direction and add that info to the SPD? Obviously, it won't be rotated, but a scaler could use that information to rotate it.

**Comment by sorgelig** [comment]
Sure, it's possible. You can make a PR for that. Since normal HDMI output allows rotation, i think it's better to have 2 flags: one is original direction (vertical/horizontal), and another is actual "rotated" flag.

**Comment by TheJesusFish** [comment]
@spinek2 you can close this. Everything is in in main and (I think) everyone is happy?

**Comment by spinek2** [comment]
OK, thank you all very much for your great commitment. I hope it will be available in the standard Mister update :) You are doing a great job, thank you.
