### ISSUE TITLE
No rom can be selected anymore if you delete the last one launched

### ISSUE THREAD

**Issue by pocomane** [MiSTer-devel/Main_MiSTer#364]
Step to reproduce:

- Select a core (e.g. NES)
- Launch a rom
- Delete the rom (e.g. from ssh or a background process)
- Open the rom-selection menu

Result

The folder tree is not shown, so you can not select any rom, until a core reset/reload

Note

I know the use scenario is not common, however I hope that this is simple enough to be implemented in the upstream Main_MiSTer distribution. It arose in the development of a [simple utility](https://github.com/pocomane/MiSTer_Batch_Control) that allows you to load a rom from the command line.

**Comment by birdybro** [comment]
This also happens with ao486 if the vhd that it was pointing to (and settings saved) is deleted, and last I checked it would persist beyond rebooting the core. It's likely related to the same behavior, since ao486 is "loading a rom" when you mount a vhd, and if you save the setting that vhd is there and referenced permanently.

**Comment by sorgelig** [comment]
I hope it's fixed with that commit.

**Comment by dfilskov** [comment]
Is the issue stil there for you guys? - Maybe it's not fixed for when deleting files in sub-dirs? - I've just run Shinobi from the MRA file in _Arcade/_S16 - then decided to delte the _S16 dir and move the file to _Aracade .... No files! appeared again when I clicked Core to open another MRA.

**Comment by dfilskov** [comment]
![image](https://user-images.githubusercontent.com/15096058/113612191-c795d400-964f-11eb-9c48-5ff964394119.png)

**Comment by pocomane** [comment]
For me the fix solved the issue. However I did not test the arcade cores, just some console ones.

**Comment by jotego** [comment]
I think this problem is still there. If you load an MRA file and then delete the folder where it was then you will need to reboot MiSTer because the OSD will hang up. The firmware should graciously fall back to opening the root folder if the last folder is gone.

**Comment by misteraddons** [comment]
I tested this and the only issue is that you can't switch cores ("No files!" warning) after loading an mra and renaming/deleting the folder with the mra. The only solution I can think of is to navigate up one directory if the source folder is missing. Otherwise, rebooting to the menu core fixes the issue.
