### ISSUE TITLE
Thrustmaster Wheel and Pedals Support

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/Main_MiSTer#681]
The pedals are the main issue and do not work properly in the PSX core, with erratic behavior depending on how far the pedals are pressed at times and gas and brake seemingly both assigned to a single pedal (brake).  MiSTer main apparently needs support to recognize Thrustmaster wheels and assign the axis correctly.

~~The wheel portion seems to work fine (in PSX core), though it has a very large deadzone in Spy Hunter arcade that makes it unplayable- can anything be done about this?~~ 
**EDIT**: This large deadzone was because of the default turning radius (900 degree) of the wheel.  The issue is fixed by using built-in hardware key combinations to limit the radius to 270 degrees for arcade games. (dpad left+mode on T300RS)

-----

Wheel: Thrustmaster T300RS

Device ID: 044f:b66e

I recorded the following data from the console for the pedals:

[throttle]
Axis:5
Range:0...1023
Default offset (nothing pressed):1019
Fully pressed offset:1

[brake]
Axis:1
Range:0...1023
Default offset (nothing pressed):1019
Fully pressed offset:1

[clutch]
Axis:6
Range:0...1023
Default offset (nothing pressed):1019
Fully pressed offset:1

**Comment by atrac17** [comment]
I fixed the mapping issues [here](https://www.patreon.com/posts/logitech-wheel-69857028). Spy Hunter may be an unbound wheel.

**Comment by M-Walrus** [comment]
I fixed the Spy Hunter deadzone issue by using a hardware key combination on the wheel to change the turning radius to 270 degrees (Dpad Left + Mode on T300RS). The 900 degree default is just too much for most arcade games to handle well, but 270 is perfect for Spy Hunter.

Pedals still are not recognized correctly on MiSTer though, for PSX core, PC Engine core with @dshadoff 's new XE-1AP analog control support, and arcade games that had analog support like Spy Hunter.

**Comment by atrac17** [comment]
I fixed the mapping issues [here](
https://www.patreon.com/posts/logitech-wheel-69857028). Spy Hunter may be
an unbound wheel.

**Comment by M-Walrus** [comment]
Thrustmaster wheels are still not working correctly with the latest linux update. They cannot even be bound past a certain point in the menu.

**Comment by sorgelig** [comment]
Fine tuning specific wheel is beyond me. To do it, i have to have every wheel. I'm not going to buy them all, sorry.

**Comment by M-Walrus** [comment]
> Fine tuning specific wheel is beyond me. To do it, i have to have every wheel. I'm not going to buy them all, sorry.

I think I have this sorted!  I had pedals bound incorrectly because I followed a guide from Zez retro I linked before- made brake applied in the wrong place.  I let him know about the typo there.

For the mapping quirks, it seems a lot of people have issues with various wheels, and it not allowing dpad/button mapping after they bind the analog axis (wheel/pedals).  I found to get around this you have to tap each pedal *very* lightly/quick.  To bind normal/digital buttons to pedal, you have to hold the pedal down halfway before entering the binding screen and then press in fully and hold, to properly bind the button.  This seems to be because it is allowing binding on both positive and negative values for the axis instead of just assigning a single function, if you just press the pedal normally.

I wrote up a guide for my specific wheel in this forum thread, but will probably make an individual thread for it, since it's a popular wheel.  I can definitely understand that you cannot test them all, so I will pool all the info about my particular wheel there:
https://misterfpga.org/viewtopic.php?p=66567#p66567

Closing this issue report.  Thanks for making MiSTer great sorg & have a good new year.
